"""Trade Thesis Engine taxonomy — Series 92. Plain string constants
(house convention, never enum.Enum)."""
from __future__ import annotations

MSI_TRADE_THESIS_VERSION = "1.0.0"
RECOGNIZED_SCHEMA_VERSIONS = ("1.0.0",)

# --- Deliverable 3: thesis types -- MARKET THESES, never strategies -----
THESIS_TREND_CONTINUATION = "TREND_CONTINUATION"
THESIS_TREND_REVERSAL = "TREND_REVERSAL"
THESIS_RANGE_PERSISTENCE = "RANGE_PERSISTENCE"
THESIS_VOLATILITY_EXPANSION = "VOLATILITY_EXPANSION"
THESIS_VOLATILITY_COMPRESSION = "VOLATILITY_COMPRESSION"
THESIS_BREAKOUT = "BREAKOUT"
THESIS_FAILED_BREAKOUT = "FAILED_BREAKOUT"
THESIS_MEAN_REVERSION = "MEAN_REVERSION"
THESIS_EVENT_RISK = "EVENT_RISK"
THESIS_NO_TRADE = "NO_TRADE"

ALL_THESIS_TYPES = (
    THESIS_TREND_CONTINUATION, THESIS_TREND_REVERSAL, THESIS_RANGE_PERSISTENCE,
    THESIS_VOLATILITY_EXPANSION, THESIS_VOLATILITY_COMPRESSION, THESIS_BREAKOUT,
    THESIS_FAILED_BREAKOUT, THESIS_MEAN_REVERSION, THESIS_EVENT_RISK, THESIS_NO_TRADE,
)

# Thesis types that carry a genuine directional expectation (as opposed to
# a pure volatility/structural view, where directional_expectation is
# still reported -- real MDI pass-through -- but is not what the thesis
# is ABOUT).
DIRECTIONAL_THESIS_TYPES = (
    THESIS_TREND_CONTINUATION, THESIS_TREND_REVERSAL, THESIS_BREAKOUT,
    THESIS_FAILED_BREAKOUT, THESIS_MEAN_REVERSION,
)

# --- Volatility expectation (always reported, regardless of thesis type) -
VOL_EXPECTATION_EXPANSION = "EXPANSION"
VOL_EXPECTATION_COMPRESSION = "COMPRESSION"
VOL_EXPECTATION_STABLE = "STABLE"
VOL_EXPECTATION_UNKNOWN = "UNKNOWN"

ALL_VOLATILITY_EXPECTATIONS = (
    VOL_EXPECTATION_EXPANSION, VOL_EXPECTATION_COMPRESSION, VOL_EXPECTATION_STABLE, VOL_EXPECTATION_UNKNOWN,
)

# --- Time horizon -- this pipeline only has daily-granularity replay
# evidence; no upstream domain supplies a duration estimate, so this is
# a single, disclosed structural convention, not derived per-thesis. ---
HORIZON_NEXT_SESSION = "NEXT_SESSION"
HORIZON_UNKNOWN = "UNKNOWN"

ALL_TIME_HORIZONS = (HORIZON_NEXT_SESSION, HORIZON_UNKNOWN)

# --- Conviction (same NONE/LOW/MODERATE/HIGH vocabulary as every prior
# MSI package) -----------------------------------------------------------
CONVICTION_NONE = "NONE"
CONVICTION_LOW = "LOW"
CONVICTION_MODERATE = "MODERATE"
CONVICTION_HIGH = "HIGH"

ALL_CONVICTION_LEVELS = (CONVICTION_NONE, CONVICTION_LOW, CONVICTION_MODERATE, CONVICTION_HIGH)

# --- Contributing domain names (Deliverable 1/7) -------------------------
DOMAIN_PRICE_STRUCTURE = "PRICE_STRUCTURE"
DOMAIN_MARKET_STRUCTURE = "MARKET_STRUCTURE"
DOMAIN_MARKET_DIRECTION = "MARKET_DIRECTION"
DOMAIN_PARTICIPANT_POSITIONING = "PARTICIPANT_POSITIONING"
DOMAIN_VOLATILITY_STRUCTURE = "VOLATILITY_STRUCTURE"
DOMAIN_CONSENSUS = "CONSENSUS"

ALL_DOMAINS = (
    DOMAIN_PRICE_STRUCTURE, DOMAIN_MARKET_STRUCTURE, DOMAIN_MARKET_DIRECTION,
    DOMAIN_PARTICIPANT_POSITIONING, DOMAIN_VOLATILITY_STRUCTURE, DOMAIN_CONSENSUS,
)

# --- Directional expectation vocabulary (pass-through of MDI's own
# taxonomy -- not re-derived, just reported) ------------------------------
DIRECTION_MIXED = "MIXED"
DIRECTION_UNKNOWN = "UNKNOWN"
DIRECTION_NEUTRAL = "NEUTRAL"
