"""Margin Bridge & Capital Fidelity taxonomy — Series 97. Plain string
constants (house convention, never enum.Enum)."""
from __future__ import annotations

MSI_MARGIN_BRIDGE_VERSION = "1.0.0"
RECOGNIZED_SCHEMA_VERSIONS = ("1.0.0",)

# --- Deliverable 2: methodology ------------------------------------------
METHODOLOGY_DEBIT_MAX_LOSS_EXACT = "DEBIT_MAX_LOSS_EXACT"
METHODOLOGY_CREDIT_SPREAD_MAX_LOSS_EXACT = "CREDIT_SPREAD_MAX_LOSS_EXACT"
METHODOLOGY_NOTIONAL_PERCENTAGE_APPROXIMATION = "NOTIONAL_PERCENTAGE_APPROXIMATION"
METHODOLOGY_PREMIUM_MULTIPLE_APPROXIMATION = "PREMIUM_MULTIPLE_APPROXIMATION"
METHODOLOGY_LIVE_BROKER_SPAN = "LIVE_BROKER_SPAN"
METHODOLOGY_UNKNOWN = "UNKNOWN"

ALL_METHODOLOGIES = (
    METHODOLOGY_DEBIT_MAX_LOSS_EXACT, METHODOLOGY_CREDIT_SPREAD_MAX_LOSS_EXACT,
    METHODOLOGY_NOTIONAL_PERCENTAGE_APPROXIMATION, METHODOLOGY_PREMIUM_MULTIPLE_APPROXIMATION,
    METHODOLOGY_LIVE_BROKER_SPAN, METHODOLOGY_UNKNOWN,
)

# --- Deliverable 4: fidelity classification -- never silently downgraded -
CONFIDENCE_EXACT = "EXACT"
CONFIDENCE_HIGH_CONFIDENCE = "HIGH_CONFIDENCE"
CONFIDENCE_APPROXIMATE = "APPROXIMATE"
CONFIDENCE_UNKNOWN = "UNKNOWN"

ALL_CONFIDENCE_LEVELS = (CONFIDENCE_EXACT, CONFIDENCE_HIGH_CONFIDENCE, CONFIDENCE_APPROXIMATE, CONFIDENCE_UNKNOWN)

# --- Data source ----------------------------------------------------------
DATA_SOURCE_LIVE_BROKER_SPAN = "LIVE_BROKER_SPAN"
DATA_SOURCE_REPLAY_TRADE_CONSTRUCTION = "REPLAY_TRADE_CONSTRUCTION"
DATA_SOURCE_REPLAY_INSUFFICIENT_DATA = "REPLAY_INSUFFICIENT_DATA"

ALL_DATA_SOURCES = (DATA_SOURCE_LIVE_BROKER_SPAN, DATA_SOURCE_REPLAY_TRADE_CONSTRUCTION, DATA_SOURCE_REPLAY_INSUFFICIENT_DATA)
