"""Portfolio & Risk Construction taxonomy — Series 91. Plain string
constants (house convention, never enum.Enum)."""
from __future__ import annotations

MSI_PORTFOLIO_CONSTRUCTION_VERSION = "1.0.0"
RECOGNIZED_SCHEMA_VERSIONS = ("1.0.0",)

# --- Approval states ---------------------------------------------------
APPROVED = "APPROVED"
REJECTED = "REJECTED"
DEFERRED = "DEFERRED"

ALL_APPROVAL_STATES = (APPROVED, REJECTED, DEFERRED)

# --- Rejection reasons (Deliverable 3) ----------------------------------
REJECT_CONSTRUCTION_NOT_SUCCESSFUL = "CONSTRUCTION_NOT_SUCCESSFUL"
REJECT_UNDEFINED_RISK_POLICY = "UNDEFINED_RISK_POLICY"
REJECT_INSUFFICIENT_CONFIDENCE = "INSUFFICIENT_CONFIDENCE"
REJECT_MISSING_MARGIN_INFORMATION = "MISSING_MARGIN_INFORMATION"
REJECT_INSUFFICIENT_CAPITAL = "INSUFFICIENT_CAPITAL"
REJECT_EXCESSIVE_CONCENTRATION = "EXCESSIVE_CONCENTRATION"
REJECT_EXCESSIVE_DIRECTIONAL_EXPOSURE = "EXCESSIVE_DIRECTIONAL_EXPOSURE"
REJECT_EXCESSIVE_VOLATILITY_EXPOSURE = "EXCESSIVE_VOLATILITY_EXPOSURE"

ALL_REJECTION_REASONS = (
    REJECT_CONSTRUCTION_NOT_SUCCESSFUL, REJECT_UNDEFINED_RISK_POLICY,
    REJECT_INSUFFICIENT_CONFIDENCE, REJECT_MISSING_MARGIN_INFORMATION,
    REJECT_INSUFFICIENT_CAPITAL, REJECT_EXCESSIVE_CONCENTRATION,
    REJECT_EXCESSIVE_DIRECTIONAL_EXPOSURE, REJECT_EXCESSIVE_VOLATILITY_EXPOSURE,
)

# --- Defer reasons -- genuinely insufficient evidence, NOT a policy
# violation (mirrors the NEUTRAL/MIXED/UNKNOWN discipline from every
# prior MSI package: "cannot decide" must never collapse into "no"). ---
DEFER_GREEKS_UNAVAILABLE = "GREEKS_UNAVAILABLE"

ALL_DEFER_REASONS = (DEFER_GREEKS_UNAVAILABLE,)

# --- Confidence levels (same vocabulary as every prior MSI package) -----
CONFIDENCE_NONE = "NONE"
CONFIDENCE_LOW = "LOW"
CONFIDENCE_MODERATE = "MODERATE"
CONFIDENCE_HIGH = "HIGH"

ALL_CONFIDENCE_LEVELS = (CONFIDENCE_NONE, CONFIDENCE_LOW, CONFIDENCE_MODERATE, CONFIDENCE_HIGH)
_CONFIDENCE_RANK = {level: i for i, level in enumerate(ALL_CONFIDENCE_LEVELS)}


def confidence_rank(level: str) -> int:
    return _CONFIDENCE_RANK[level]


# --- Deliverable 5: honest "cannot size" sentinel -----------------------
SIZE_UNKNOWN = "SIZE_UNKNOWN"

# --- Concentration dimensions --------------------------------------------
DIMENSION_STRATEGY_FAMILY = "STRATEGY_FAMILY"
DIMENSION_EXPIRY = "EXPIRY"
DIMENSION_UNDERLYING = "UNDERLYING"

ALL_CONCENTRATION_DIMENSIONS = (DIMENSION_STRATEGY_FAMILY, DIMENSION_EXPIRY, DIMENSION_UNDERLYING)
