"""MIL Next vocabulary -- finite, closed vocabularies only."""
from __future__ import annotations

MIL_NEXT_VERSION = "0.1.0"

# -- Data quality ----------------------------------------------------------
FRESHNESS_FRESH = "FRESH"
FRESHNESS_WARNING = "WARNING"
FRESHNESS_STALE = "STALE"
FRESHNESS_UNKNOWN = "UNKNOWN"
ALL_FRESHNESS = (FRESHNESS_FRESH, FRESHNESS_WARNING, FRESHNESS_STALE, FRESHNESS_UNKNOWN)

COMPLETENESS_GAP_DETECTED = "GAP_DETECTED"
COMPLETENESS_CONNECTED_NO_GAP_SIGNAL = "CONNECTED_NO_GAP_SIGNAL"
COMPLETENESS_MAX_SILENCE_EXCEEDED = "MAX_SILENCE_EXCEEDED"
COMPLETENESS_UNKNOWN = "UNKNOWN"
ALL_COMPLETENESS = (
    COMPLETENESS_GAP_DETECTED, COMPLETENESS_CONNECTED_NO_GAP_SIGNAL,
    COMPLETENESS_MAX_SILENCE_EXCEEDED, COMPLETENESS_UNKNOWN,
)

TRANSPORT_LATENCY_MEASURED = "MEASURED"
TRANSPORT_LATENCY_NOT_MEASURABLE_SYNTHETIC_EVENT_TIME = "NOT_MEASURABLE_SYNTHETIC_EVENT_TIME"
TRANSPORT_LATENCY_MEASURED_BUT_UNTRUSTED_CLOCK_SKEW = "MEASURED_BUT_UNTRUSTED_CLOCK_SKEW"
ALL_TRANSPORT_LATENCY_STATUS = (
    TRANSPORT_LATENCY_MEASURED,
    TRANSPORT_LATENCY_NOT_MEASURABLE_SYNTHETIC_EVENT_TIME,
    TRANSPORT_LATENCY_MEASURED_BUT_UNTRUSTED_CLOCK_SKEW,
)

FEED_DISAGREEMENT_NONE = "NONE"
FEED_DISAGREEMENT_WITHIN_TOLERANCE = "WITHIN_TOLERANCE"
FEED_DISAGREEMENT_BREACHED = "BREACHED"
ALL_FEED_DISAGREEMENT_STATES = (
    FEED_DISAGREEMENT_NONE, FEED_DISAGREEMENT_WITHIN_TOLERANCE, FEED_DISAGREEMENT_BREACHED,
)

# -- Timeframes --------------------------------------------------------------
TIMEFRAME_1M = "1m"
TIMEFRAME_5M = "5m"
TIMEFRAME_15M = "15m"
TIMEFRAME_SESSION = "SESSION"
ALL_TIMEFRAMES = (TIMEFRAME_1M, TIMEFRAME_5M, TIMEFRAME_15M, TIMEFRAME_SESSION)

TIMEFRAME_AGREEMENT_UNANIMOUS = "UNANIMOUS"
TIMEFRAME_AGREEMENT_MAJORITY = "MAJORITY"
TIMEFRAME_AGREEMENT_SPLIT = "SPLIT"
TIMEFRAME_AGREEMENT_INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
ALL_TIMEFRAME_AGREEMENT = (
    TIMEFRAME_AGREEMENT_UNANIMOUS, TIMEFRAME_AGREEMENT_MAJORITY,
    TIMEFRAME_AGREEMENT_SPLIT, TIMEFRAME_AGREEMENT_INSUFFICIENT_EVIDENCE,
)

# -- Regime (VSB-owned only -- trend/range/breakout belong to PSI/MSSI, never here) --
REGIME_TRANSITIONING = "TRANSITIONING"
REGIME_VOLATILITY_EXPANSION = "VOLATILITY_EXPANSION"
REGIME_LIQUIDITY_STRESS = "LIQUIDITY_STRESS"
REGIME_SHOCK_LIKE = "SHOCK_LIKE"
REGIME_CALM = "CALM"
REGIME_UNKNOWN = "UNKNOWN"
ALL_REGIMES = (
    REGIME_TRANSITIONING, REGIME_VOLATILITY_EXPANSION, REGIME_LIQUIDITY_STRESS,
    REGIME_SHOCK_LIKE, REGIME_CALM, REGIME_UNKNOWN,
)

DIRECTION_BULLISH = "BULLISH"
DIRECTION_BEARISH = "BEARISH"
DIRECTION_NEUTRAL = "NEUTRAL"
DIRECTION_UNKNOWN = "UNKNOWN"
ALL_DIRECTIONS = (DIRECTION_BULLISH, DIRECTION_BEARISH, DIRECTION_NEUTRAL, DIRECTION_UNKNOWN)

# -- Liquidity -----------------------------------------------------------
LIQUIDITY_UNKNOWN = "LIQUIDITY_UNKNOWN"
LIQUIDITY_NORMAL = "LIQUIDITY_NORMAL"
LIQUIDITY_STRESSED = "LIQUIDITY_STRESSED"
ALL_LIQUIDITY = (LIQUIDITY_UNKNOWN, LIQUIDITY_NORMAL, LIQUIDITY_STRESSED)

# -- OI ---------------------------------------------------------------------
OI_WEIGHT_NONE = "NONE"
OI_WEIGHT_LOW = "LOW"
OI_WEIGHT_MODERATE = "MODERATE"
ALL_OI_WEIGHTS = (OI_WEIGHT_NONE, OI_WEIGHT_LOW, OI_WEIGHT_MODERATE)

# -- Event calendar -----------------------------------------------------------
KNOWN_NO_EVENT = "KNOWN_NO_EVENT"
KNOWN_EVENT = "KNOWN_EVENT"
COVERAGE_UNKNOWN = "COVERAGE_UNKNOWN"
ALL_EVENT_RISK_STATES = (KNOWN_NO_EVENT, KNOWN_EVENT, COVERAGE_UNKNOWN)

# -- Contradiction -------------------------------------------------------------
CONTRADICTION_LOW = "LOW"
CONTRADICTION_MODERATE = "MODERATE"
CONTRADICTION_HIGH = "HIGH"
ALL_CONTRADICTION_LEVELS = (CONTRADICTION_LOW, CONTRADICTION_MODERATE, CONTRADICTION_HIGH)

# -- Posture -- ONLY these five are ever permitted -----------------------------
POSTURE_NORMAL = "NORMAL"
POSTURE_REDUCED = "REDUCED"
POSTURE_DEFINED_RISK_ONLY = "DEFINED_RISK_ONLY"
POSTURE_MANAGE_ONLY = "MANAGE_ONLY"
POSTURE_NO_TRADE = "NO_TRADE"
ALL_POSTURES = (
    POSTURE_NORMAL, POSTURE_REDUCED, POSTURE_DEFINED_RISK_ONLY,
    POSTURE_MANAGE_ONLY, POSTURE_NO_TRADE,
)

NOT_EVALUATED_DUE_TO_DATA_FAILURE = "NOT_EVALUATED_DUE_TO_DATA_FAILURE"
