"""Strategy Expression Engine taxonomy — Series 93. Plain string
constants (house convention, never enum.Enum)."""
from __future__ import annotations

MSI_STRATEGY_EXPRESSION_VERSION = "1.0.0"
RECOGNIZED_SCHEMA_VERSIONS = ("1.0.0",)

# --- Deliverable 3: reusable strategy characteristics -- describe
# EXPOSURE, never a named strategy. ---------------------------------------
CHAR_DIRECTIONAL = "DIRECTIONAL"
CHAR_DELTA_NEUTRAL = "DELTA_NEUTRAL"
CHAR_LONG_VOLATILITY = "LONG_VOLATILITY"
CHAR_SHORT_VOLATILITY = "SHORT_VOLATILITY"
CHAR_POSITIVE_THETA = "POSITIVE_THETA"
CHAR_NEGATIVE_THETA = "NEGATIVE_THETA"
CHAR_DEFINED_RISK = "DEFINED_RISK"
CHAR_UNDEFINED_RISK = "UNDEFINED_RISK"
CHAR_DEBIT = "DEBIT"
CHAR_CREDIT = "CREDIT"
CHAR_LIMITED_PROFIT = "LIMITED_PROFIT"
CHAR_UNLIMITED_PROFIT = "UNLIMITED_PROFIT"
CHAR_LIMITED_LOSS = "LIMITED_LOSS"
CHAR_UNLIMITED_LOSS = "UNLIMITED_LOSS"
CHAR_POSITIVE_CONVEXITY = "POSITIVE_CONVEXITY"
CHAR_NEGATIVE_CONVEXITY = "NEGATIVE_CONVEXITY"

ALL_CHARACTERISTICS = (
    CHAR_DIRECTIONAL, CHAR_DELTA_NEUTRAL, CHAR_LONG_VOLATILITY, CHAR_SHORT_VOLATILITY,
    CHAR_POSITIVE_THETA, CHAR_NEGATIVE_THETA, CHAR_DEFINED_RISK, CHAR_UNDEFINED_RISK,
    CHAR_DEBIT, CHAR_CREDIT, CHAR_LIMITED_PROFIT, CHAR_UNLIMITED_PROFIT,
    CHAR_LIMITED_LOSS, CHAR_UNLIMITED_LOSS, CHAR_POSITIVE_CONVEXITY, CHAR_NEGATIVE_CONVEXITY,
)

# --- Desired-exposure summary axes (Deliverable 2 fields) -----------------
VOLATILITY_EXPOSURE_LONG = "LONG_VOLATILITY"
VOLATILITY_EXPOSURE_SHORT = "SHORT_VOLATILITY"
VOLATILITY_EXPOSURE_EITHER = "EITHER"
VOLATILITY_EXPOSURE_UNKNOWN = "UNKNOWN"

RISK_PROFILE_DEFINED = "DEFINED_RISK"
RISK_PROFILE_UNDEFINED = "UNDEFINED_RISK"
RISK_PROFILE_EITHER = "EITHER"
RISK_PROFILE_UNKNOWN = "UNKNOWN"

TIME_DECAY_POSITIVE = "POSITIVE_THETA"
TIME_DECAY_NEGATIVE = "NEGATIVE_THETA"
TIME_DECAY_EITHER = "EITHER"
TIME_DECAY_UNKNOWN = "UNKNOWN"

CONVEXITY_POSITIVE = "POSITIVE_CONVEXITY"
CONVEXITY_NEGATIVE = "NEGATIVE_CONVEXITY"
CONVEXITY_EITHER = "EITHER"
CONVEXITY_UNKNOWN = "UNKNOWN"

DIRECTION_DIRECTIONAL = "DIRECTIONAL"
DIRECTION_DELTA_NEUTRAL = "DELTA_NEUTRAL"
DIRECTION_EITHER = "EITHER"
DIRECTION_UNKNOWN = "UNKNOWN"
